print("Mam na imię Marcin!")
print("Mam na imię Marcin!")
print("Mam na imię Marcin!")
print("Mam na imię Marcin!")
print("Mam na imię Marcin!")
print("Mam na imię Marcin!")
print("Mam na imię Marcin!")
